// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /tickets"
  | "GET /tickets/{ticketId}"
  | "PATCH /tickets/{ticketId}/draft"
  | "POST /tickets"
  | "POST /tickets/{ticketId}/approve"
  | "POST /tickets/{ticketId}/resolve";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /tickets": { kind: "scope", scope: "tickets:read-all" },
  "GET /tickets/{ticketId}": { kind: "scope", scope: "tickets:read-all" },
  "PATCH /tickets/{ticketId}/draft": { kind: "scope", scope: "tickets:edit-draft" },
  "POST /tickets": { kind: "public" },
  "POST /tickets/{ticketId}/approve": { kind: "scope", scope: "tickets:approve" },
  "POST /tickets/{ticketId}/resolve": { kind: "scope", scope: "tickets:resolve" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
