// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "tickets:approve"
  | "tickets:edit-draft"
  | "tickets:read-all"
  | "tickets:resolve";

export type Role =
  | "SupportAgent";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["tickets:approve", "tickets:edit-draft", "tickets:read-all", "tickets:resolve"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["SupportAgent"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "SupportAgent": ["tickets:approve", "tickets:edit-draft", "tickets:read-all", "tickets:resolve"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "SupportAgent": ["Support Agents"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "SupportAgent": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
